import { defineCollection, reference } from 'astro:content';
import { glob } from 'astro/loaders';
// `import { z } from 'astro:content'` is deprecated in Astro 7 in favour of
// this path; the re-export is scheduled for removal.
import { z } from 'astro/zod';
import { LOCALES } from './i18n/config';

/**
 * Content collections.
 *
 * Authoring rule, in one sentence each:
 *   - Short fields → one file, both languages inside it.
 *   - Long markdown bodies → one file per language, and the folder is the language.
 *
 * The split is not arbitrary. Members share a photograph and a sort order, so
 * two files per person would let those drift apart for no benefit. Product
 * programmes have long prose bodies, which a frontmatter field cannot hold.
 *
 * Every collection carries `published`. Nothing is on the site until someone
 * sets it to true — which is how the product pages can be written in full now
 * and released later, and how a team profile waits for the person's consent.
 */

/**
 * Each `translations` block below is written out per collection rather than
 * generated by a helper. A generic helper looked tidier but erased the field
 * types at the call site, so `text.title` came back as `{}` — worth a few extra
 * lines to keep the schema legible and the types exact.
 *
 * `en` is `.optional()`, not `.partial()`: a language block is complete or
 * absent. Half-filled translations are the failure mode worth preventing.
 */

const productLineText = z.object({
  title: z.string().min(1),
  summary: z.string().default(''),
  /** Alt text is language-specific, so it lives inside the translation. */
  coverAlt: z.string().optional(),
});

const memberText = z.object({
  name: z.string().min(1),
  role: z.string().min(1),
  bio: z.string().default(''),
  photoAlt: z.string().optional(),
});

/**
 * The five standing product lines: sport, health, household, home-care
 * technology, educational toys. These are categories, not products — they change
 * rarely, and every product belongs to one.
 */
const productLines = defineCollection({
  loader: glob({ pattern: ['*.md', '!_*.md'], base: './src/content/product-lines' }),
  schema: z.object({
    order: z.number().int().nonnegative().default(99),
    published: z.boolean().default(false),
    /** Path under public/, e.g. /images/product-lines/sport.jpg */
    cover: z.string().startsWith('/').optional(),
    translations: z.object({
      'zh-TW': productLineText,
      en: productLineText.optional(),
    }),
  }),
});

/**
 * Individual products and concept programmes.
 *
 * Folder is the language, filename is the slug: `zh-TW/foo.md` and `en/foo.md`
 * are the same product. Nothing to typo, nothing to keep in sync.
 *
 * Detail pages are not built yet — the designer dropped the slide-out panel and
 * has not replaced it. The schema is ready so the writing can start regardless.
 */
const products = defineCollection({
  loader: glob({
    pattern: ['zh-TW/*.md', 'en/*.md', '!**/_*.md'],
    base: './src/content/products',
    generateId: ({ entry }) => {
      const match = /^(zh-TW|en)\/([^/]+)\.mdx?$/.exec(entry);
      if (!match) {
        throw new Error(
          `Product "${entry}" must be at src/content/products/<zh-TW|en>/<slug>.md with no nesting.`,
        );
      }
      const [, locale, slug] = match;
      // A slug matching a locale code would collide with the /en/ URL prefix.
      if ((LOCALES as readonly string[]).includes(slug)) {
        throw new Error(`Product slug "${slug}" is reserved — it is a locale code.`);
      }
      return `${locale}/${slug}`;
    },
  }),
  schema: z.object({
    title: z.string().min(1),
    summary: z.string().min(1),
    line: reference('productLines'),
    /** Where this sits in development. Shown as a label, not a promise of a date. */
    status: z.enum(['concept', 'in-development', 'launched']).default('concept'),
    cover: z.string().startsWith('/').optional(),
    coverAlt: z.string().optional(),
    order: z.number().int().nonnegative().default(99),
    published: z.boolean().default(false),
  }),
});

/**
 * Team members.
 *
 * Required for the About section — grant reviewers and prospective investors
 * read it as evidence the company can do what it says. Publish only with the
 * person's consent; `published` defaults to false so that is the safe path.
 */
const members = defineCollection({
  loader: glob({ pattern: ['*.md', '!_*.md'], base: './src/content/members' }),
  schema: z.object({
    order: z.number().int().nonnegative().default(99),
    published: z.boolean().default(false),
    /** Path under public/, e.g. /images/members/name.jpg. At least 640×800. */
    photo: z.string().startsWith('/').optional(),
    translations: z.object({
      'zh-TW': memberText,
      en: memberText.optional(),
    }),
  }),
});

export const collections = { productLines, products, members };
